### ISSUE TITLE
v0.0.5.905

### ISSUE THREAD

**Issue by black-okean** [completely-burned/glowing-octo-shame-arma2#236]
Предлагаю потратить на меню.
Нужно учесть:
Телепорт казармы, аэропорты и роли.
Возможность захвата здания в городе.
Строительство базы, camps, укрепления.

**Comment by completely-burned** [comment]
Беспилотники также нужно учитывать.

**Comment by user-hq** [comment]
Функцию сжатия нужна, потому что много повторяющихся данных в меню.

**Comment by lunar-balance** [comment]
Как всегда у меня не получается следовать плану.

**Comment by notconsequents** [comment]
Сделаю ящикам A3 на базе восстановление содержимого как в A2, и можно релиз.

**Comment by notconsequents** [comment]
Связывать задачи с версией - плохая идея.
