### ISSUE TITLE
Error Undefined variable in expression: _testpos

### ISSUE THREAD

**Issue by completely-burned** [completely-burned/glowing-octo-shame-arma2#7]
https://github.com/fearOfSociety/glowing-octo-shame-arma2/blob/671a02f2db973cb699e9767b0116b0079b0a751a/glowing-octo-shame.Chernarus/m/functions/m_fnc_waypoints.sqf#L363

**Comment by fearOfSociety** [comment]
#9 fixed 71e7daa36722bfa4145d57e5c5634c38defc6f4c
